[[sin-replacement-jews-christians]]
= Christians and Jews Given for Sin in the Quran

== Introduction
[quote, Surah Al-Nahl 16:25]
 So they will bear their own burdens in full on the Day of Resurrection, and also some of the burdens of those without knowledge whom they misled. Unquestionably, evil is that which they bear.

The quran contradicts itself by saying that every soul **will bear its own burden** on the Day of Resurrection, yet it also says that that **Muslims will be given a Jew or a Christian in their place to bear their sins**. This is a contradiction in the quran.

== The Quranic Verses

.Jews and Christians are given for the sins of Muslims
[quote, Sahih Muslim 2767a]
When it will be the Day of Resurrection Allah would deliver to every Muslim a Jew or a Christian and say: That is your rescue from Hell-Fire. 

.Jews and Christians will be in Hell-Fire in place of Muslims
[quote, Sahih Muslim 2767b]
No Muslim would die but Allah would admit in his stead a Jew or a Christian in Hell-Fire. 'Umar b. Abd al-'Aziz took an oath: By One besides Whom there is no god but He, thrice that his father had narrated that to him from Allah's Messenger (ﷺ).
(Sahih Muslim 2767)