[[sin-replacement-jews-christians]]
= Christians and Jews Given for Sin in the Quran


== Introduction

[quote, Surah Al-Nahl 16:25]
 So they will bear their own burdens in full on the Day of Resurrection, and also some of the burdens of those without knowledge whom they misled. Unquestionably, evil is that which they bear.

The quran contradicts itself by saying that every soul **will bear its own burden** on the Day of Resurrection, yet it also says that that **Muslims will be given a Jew or a Christian in their place to bear their sins**. This is a contradiction in the quran.

== The Hadith Verses

.Jews and Christians are given for the sins of Muslims
[quote, Sahih Muslim 2767a]
When it will be the Day of Resurrection Allah would deliver to every Muslim a Jew or a Christian and say: That is your rescue from Hell-Fire. 

.Jews and Christians will be in Hell-Fire in place of Muslims
[quote, Sahih Muslim 2767b]
No Muslim would die but Allah would admit in his stead a Jew or a Christian in Hell-Fire. 'Umar b. Abd al-'Aziz took an oath: By One besides Whom there is no god but He, thrice that his father had narrated that to him from Allah's Messenger (ﷺ).

 Proof that mohammad was a crossdresser who identifies as a women (transgender)
He wore his wives garments and dress.
Muhammad was the world's first and only cross-dressing prophet. 
Proof of atleast 4 verses in 
From the Sahih Collection of al-Bukhari, Hadith Number 2442
From Sahih al-Bukhari, Hadith Number 2393
From Sahih al-Bukhari, Hadith Number 3941
From the Sahih collection of Imam Muslim, Hadith Number 4472
Full info here - https://answering-islam.org/Responses/Abualrub/mhd_cross_dressing1.htm

Hadith 4953
