= Christian Polemics Against Islam

**Polemics** means attack or controversy. Polemics in this case is the study of the controversies surrounding Islam. This module will explore the controversies surrounding Islam and the Islamic faith. 

**Apologetics** is the study of defending a position. We use apologetics to  defend Christianity as we are commanded to do so. So the Christian is called to use both Polemics and Apologetics in the defense of the faith.

This module will explore the controversies surrounding Islam and the Islamic faith.

The standard islamic narrative (SIN)

Problems with Mecca::
Mecca is where Adam and Eve were thrown down to, from the Garden of Eden (Surah 7:24) So the Garden of Eden is up in space somewhere. 

The Torah says the **Garden of Eden was on Earth**. So we have **a contradiction** between the Quran and the Torah. Not only this but Adam was thrown down to Sir Lanka and Eve was thrown down to Mecca. So we have a contradiction between the Quran and the Hadiths. The Hadiths say that Adam and Eve were **thrown down to the same place**. So we have a contradiction between the Quran and the Hadiths.

Two very important points are missed in the Qurans account. 

1. In the Torah God was in the garden of Eden. Walking and talking in the cool of the day. **God is missing from the Quran in the garden in space.**
2. If God is missing from the Quran in the garden in space, **then Allah cannot enter time and space.**

This means God never had a relationship with man from the beginning in Islam.



Mecca is where Abraham lived when he destroyed the idols within the Ka'aba (Surah 21:51-71)

Mecca is the center of trade North, South, East and West (Montgomery Watt's Trade Route Theory)

So it should be one of the best known and best documented places in history. But it is not.



Problems with the Quran::


Problems with Muhammed::

Muhammed has no grave. 







