[[pagan-black-stone]]
= Kissing the Pagan Black Stone

The Black Stone is a sacred stone in Islam that is located in the Kaaba in Mecca. It is believed to have been sent down from heaven by Allah. The kaaba is Allah's house. The black stone is kissed by pilgrims during the Hajj and Umrah as a sign of respect and devotion and worship. The black stone is a pagan practice that has been incorporated into Islam.

According to tradition, this stone was given to Adam on his expulsion from paradise (In space) in order to obtain forgiveness of his sins.

[quote, Sunan an-Nasa'i 2935]
"O Abu abdur-Rahman, why do I only see you touching these two corners?" He said: "I heard the Messenger of Allah say: **'Touching them erases sins.'** And I head him say: 'whoever circumambulates seven times, **it is like freeing a slave.**'"

The stone was once white, but it has turned black due to the sins of the people who have touched it.

[quote, Sunan an-Nasa'i 2931]
It was narrated that Ibn 'Abbas said: "The Messenger of Allah said concerning the Black Stone: **'By Allah, Allah will bring it forth on the Day of Resurrection, and it will have two eyes with which it will see, and a tongue with which it will speak, bearing witness for those who touched it in sincerity.'**"


This stone has eyes and a tongue and will speak on the day of judgement. So is this a pagan practice or not?









